# Generated by Django 4.2.7 on 2023-11-28 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0003_rename_questions_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="course",
            new_name="question",
        ),
    ]
